apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: dev-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - delete
  - list
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - update
  - delete
  - list
  - create
